# Generated by Django 4.2.3 on 2023-09-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_reaction_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'post')},
        ),
    ]
